{% set name = "iso4217" %}
{% set version = "1.12.20240625" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5756023b09f017ef59caa7017d0dfda7267419b12611b44f9e178c33598ab579

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - iso4217
    - iso4217.test

about:
  home: https://github.com/dahlia/iso4217
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  summary: ISO 4217 currency data package for Python

  doc_url: ''
  dev_url: https://github.com/dahlia/iso4217

extra:
  recipe-maintainers:
    - gerrymanoim
    - jbredeche
    - jdricklefs
    - llllllllll
    - richafrank
